app:
  datasources:
    first:
      name: poc
      schema: public
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${app.datasources.first.host}:${app.datasources.first.port}/${app.datasources.first.name}?currentSchema=${app.datasources.first.schema}

      host: 10.88.160.3
      port: 5432
      credentials:
        username: davide
        password: "d4v1d3%3cr3t"

    second:
      name: poc
      schema: public
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${app.datasources.second.host}:${app.datasources.second.port}/${app.datasources.second.name}

quarkus:
  datasource:
    db-kind: postgresql
    username: ${app.datasources.first.credentials.username}
    password: ${app.datasources.first.credentials.password}
    jdbc:
      url: ${app.datasources.first.url}
      max-size: 8
      min-size: 2

  http:
    port: 8081
    root-path: /quarkus/api
